### ISSUE TITLE
bringing a line of code down to the command window.

### ISSUE THREAD

**Issue by ASH-II** [ZXDunny/SpecBAS#1] opened 2019-12-20 20:25 UTC
```
10 PRINT at 0,0;SCALE 8,8;HOUR TIME;":";MINUTES TIME;":";SECONDS TIME
20 PAUSE 1
30 GO TO 10
```
this is a simple clock but when I hit TAB on line 10 to edit it in the command window it hangs.

**Comment by ZXDunny** [comment] 2019-12-20 20:53
Cannot reproduce - I highlight line 10 with CTRL+Up/Down as necessary, then press TAB from the Direct command window. No issues here, but I'll test some more as I go. Possibly already fixed.

Try grabbing the binary from the front page here:
https://github.com/ZXDunny/SpecBAS/blob/master/SpecBAS.exe

And see if it's still a problem.

**Comment by ASH-II** [comment] 2019-12-20 20:58
Yeah it’s just started....it’s was fine and then it started to hang, it’s any code I enter now. Errr I will restart and see if that helps.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by ASH-II** [comment] 2019-12-20 21:12
So I restarted and if I paste a some random code off Roseta Stone I can edit it in the command window

10 REM First we draw the clock face
20 FOR n=1 TO 12
30 PRINT aT 10-10*COS (n/6*PI),16+10*SIN (n/6*PI);n
40 NEXT n
50 rem DEF FN t()=INT (65536*PEEK 23674+256*PEEK 23673+PEEK 23672)/50: REM number of seconds since start
100 REM Now we start the clock
110 rem LET t1=FN t()
120 LET a=t1/30*PI: REM a is the angle of the second hand in radians
130 LET sx=72*SIN a: LET sy=72*COS a
140 PLOT 131,91: DRAW OVER 1;sx,sy: REM draw hand
200 rem LET t=FN t()
210 IF INT t<=INT t1 THEN GO TO 200: REM wait for time for next hand; the INTs were not in the original but force it to wait for the next second
220 PLOT 131,91: DRAW OVER 1;sx,sy: REM rub out old hand
230 LET t1=t: GO TO 120

I then started deleting lines and testing the tabbing down, when I got to  four lines it would crash, so for me it is the number of lines, 4 or less and it will hang.

10 REM First we draw the clock face
20 FOR n=1 TO 12
30 PRINT aT 10-10*COS (n/6*PI),16+10*SIN (n/6*PI);n
40 NEXT n


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by ZXDunny** [comment] 2019-12-20 23:45
Ok, found the issue - fix committed. You can go grab the SpecBAS.exe file mentioned earlier and verify it's sorted.

**Comment by ASH-II** [comment] 2019-12-21 05:38
Yep that works.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Closed as completed** 2019-12-21 09:04 UTC
